In [2]:
import numpy as np

#these functions are valid only for numpy n-dimensional array
#consider vector and matrices(arrays) same
a=np.random.randn(5)
print(a)
#this creates 5 gaussian random variables stored in array a

[ 0.29480205 -1.0654036  -1.06042475 -0.34477895  0.08223492]


In [7]:
print(a.shape)
#note that shape is not a method .it is an attribute
#it turns out this is neither a row vector nor a column vector
# instead its a different data structure called rand 1 array which doesn't behave like a normal vector as shown below

(5,)


In [8]:
print(a.T)
#transpose is exactly the same as a which is not expected for a matrix

[-0.22610687  0.46300967 -0.89970423  0.96790806 -1.58418022]


In [4]:
print(np.dot(a,a.T))
#np.dot() function takes 2 matrices as parameters and is equivalent to matrix multiplication
# in case of 2-d arrays and inner product of the vectors in case of 1-d arrays
#outer product is the other name of matrix multiplication and inner product is the component wise product
#instead of obtaining matrix you get a number!!so it is highly recommended to be careful of rank 1 array

2.4721288163847994


In [9]:
#when you encounter rank 1 array you can solve the probleam as follows
#method 1
a=np.random.randn(5,1)
print(a)
#method 2
a=np.random.randn(5)
a=a.reshape((5,1))
print(a,a.shape)

[[0.06080234]
 [0.85180307]
 [0.09905157]
 [1.48995205]
 [0.02785127]]
[[-0.83338225]
 [ 0.82207414]
 [ 1.47694284]
 [ 1.21084485]
 [ 0.52010832]] (5, 1)


In [10]:
print(np.dot(a,a.T))
#now this will give outer product/matrix multiplication

[[ 0.69452598 -0.685102   -1.23085795 -1.00909661 -0.43344904]
 [-0.685102    0.67580589  1.21415651  0.99540424  0.4275676 ]
 [-1.23085795  1.21415651  2.18136015  1.78834862  0.76817026]
 [-1.00909661  0.99540424  1.78834862  1.46614524  0.62977048]
 [-0.43344904  0.4275676   0.76817026  0.62977048  0.27051266]]


In [22]:
b = np.array([(8,9,10),(11,12,13)])
print(b)
b=b.reshape((3,2))
print(b)
#

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [15]:
b=np.ndim([[1,2],3,4])
c=np.ndim([[1,2],[2,3]])
c=[1,2]
print(b,c)

1 2


In [18]:
print(a.dtype,a.size,a.itemsize)
#a.dtype find the data type of the elements that are stored in an array
#a.itemsize calculate the byte size of each element
#a.size calculate total no of elements
c=[1,2.2]
print(a.dtype,a.itemsize)
#it seems as if c has 1 int and 1 float but python considers both as float when one of them is float

float64 5 8
float64 8


In [23]:
#slicing
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])
#array(1,2,3,4) is your index 0 and (3,4,5,6) is index 1 of the python numpy array. 
#Therefore, we have printed the second element from the zeroth index
print(a[0:,2])
#this gives us the 2nd element from the zeroth and first index of the array.
#colon represents all the rows, including zero
a=np.array([(8,9),(10,11),(12,13)])
print(a[0:2,1])
#if we have one more row and we don’t want to get its 2nd element printed just as the image above
#NOTE- this is valid when array is 2d that is it has m rows and n columns unlike arrays like [1,[2,3]].
#it is not a 2-d numpy array instead if a rank 1 array as if u print its shape it will print (2,)

3
[3 5]
[ 9 11]


In [38]:
a=np.linspace(1,3,10)
print(a)
#np.linspace() is a operation in python numpy which returns evenly spaced numbers over a specified interval

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [28]:
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())
#a.sum() prints all the elements of a multidimensional array
#NOTE the word multidimensional.If you perform this operation on a list that is not a multi/uni dimensional 
#array like rank 1 array then you will not get desired results.

1
3
6


In [30]:
#in numpy rows are called as axis 1 and the columns are called as axis 0
a= np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=0))
print(a.sum(axis=1))
#the sum of all the columns are added where 1+3=4, 2+4=6 and 3+5=8. Similarly, if you replace the axis by 1, 
#then it will print [6 12] where all the rows get added.

[4 6 8]
[ 6 12]


In [31]:
a=np.array([(1,2,3),(3,4,5)])
print(np.sqrt(a))
print(np.std(a))
#np.sqrt() calculate square root of all the elements
#np.std() calculate standard deviation i.e how much each element varies from the mean value of the python numpy array

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [32]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)
#x*y gives inner product of the vectors x,y

[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [33]:
#Vertical & Horizontal Stacking
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))
#to concatenate two arrays and not just add them, you can perform it using two ways -
#vertical stacking and horizontal stacking

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [35]:
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel(),x.ravel().shape)
#x.ravel() is used to convert one numpy array into a single column i.e ravel.
#it returns a rank 1 array .Be careful
#this function works fine for rank 1 array as well

[1 2 3 3 4 5] (6,)


In [37]:
print(np.arange(4, 20, 3))
#np.arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval.
#start:start of interval range. By default start = 0
#stop:end of interval range(NOTE THAT STOP VALUE IS NOT INCLUDED IN THE ARRAY BUT START VALUE IS)
#step:step size of interval. By default step size = 1,  
#dtype : type of output array

#similar to linespace but the only difference is that in linespace we provide no of elements that the array should 
#have and both start and stop value is included unlike inarange in which resulted array doesn't have stop value  

[ 4  7 10 13 16 19]


In [40]:
#special functions
x= np.arange(0,3*np.pi,0.1)
#np.pi is the value of pi constant
y=np.sin(x)
z=np.tan(x)

In [36]:
a= np.array([1,2,3])
print(np.exp(a))     #exponential function
print(np.log(a))     #natural log
print(np.log10(a))   #log base 10

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
